#!/usr/bin/perl
# Documentation before the code#{{{
=head1 NAME 

B<coreload> - prepare a MySQL database for running Forage

=head1 SYNOPSIS

B<coreload> FASTAFILE

=head1 DESCRIPTION

Prepares a core orthologs table for running Forage. Basically, reads a fasta file
and loads its content into the database. Due to the usage of the MySQL LOAD
INFILE command, this process is pretty fast. 

The fasta headers need to be formatted in a certain way:

  >HMM|TAXON|ID

where HMM is the name of the pHMM that will be used for searching, TAXON the taxon name of the sequence in question, and ID a sequence identifier. None of these need to be unique, but the combination of all three must be.

B<coreload> expects a certain table structure. You may create it yourself by hand
using the following SQL statement or whatever workflow you fancy, or you may run
B<coreload -c> once, which does the same thing.

	DROP TABLE IF EXISTS core_orthologs;
  CREATE TABLE core_orthologs (
    id          INT(11) AUTO_INCREMENT PRIMARY KEY,
    taxon       VARCHAR(255) NOT NULL,
    orthoset    VARCHAR(255) NOT NULL,
    hmm         VARCHAR(255) NOT NULL,
    blastdb     VARCHAR(255) NOT NULL, INDEX (blastdb),
    header      VARCHAR(255) NOT NULL, INDEX (header),
    sequence    MEDIUMBLOB);

=cut#}}}

use strict;
use warnings;
use Carp;
use Getopt::Long;
use File::Temp;     # temporary files
use File::Spec;
use Seqload::Fasta qw(fasta2csv); # object-oriented access to fasta files, fasta2csv converter
use DBI;
use DBD::mysql;
use Seqload::Fasta;


my $dbname   = 'forage';
my $dbserver = '127.0.0.1';
my $user     = undef;
my $pwd      = undef;
my $setname  = undef;
my $prefix   = 'o_';
my $create   = 0;
my $table = 'bl';
my @tables = qw(
	blast_dbs
	ogs
	ortholog_set
	sequence_pairs
	sequences_aa
	sequences_nt
	set_details
	taxa
	users
);

#{{{POD: Options
=head1 OPTIONS

=head2 -c

(Re-)creates the necessary table structure. Careful, this will wipe out everything
you had in the table. You should not do this more than once in the process of using
Forage unless you know what you are doing.

=head2 -D database

Database name to use. Defaults to 'forage'.

=head2 -h host

Database server. Defaults to '127.0.0.1', which is (mostly) equivalent to
'localhost'.

=head2 -b /blast/database/prefix

BLAST database prefix. Must point to a directory containing the BLAST databases. These themselves must be each in its own directory, e.g., like so:

  /home/user/blast/apismellifera
  /home/user/blast/drosophilamelanogaster

The directory name of each BLAST database must match with the taxon name in the fasta headers, and the BLAST database inside it must be named as F<taxon_prot>.

If all is setup like described, the prefix would be specified as: B<-b /home/user/blast>.

=head2 -p password

Password for the connection. No default; this must be set.

=head2 -t table

Table name to use. Defaults to 'core_orthologs'.

=head2 -u username

Username for the connection. No default; this must be set.

=cut#}}}

GetOptions(
	'D=s'      => \$dbname,
	'prefix=s' => \$prefix,
	'c'        => \$create,
	'h=s'      => \$dbserver,
	'p=s'      => \$pwd,
	's=s'      => \$setname,
	't=s'      => \$table,
	'u=s'      => \$user,
	);

# make sure there is at least one underscore at the end of the prefix
$prefix =~ s/_$//;
$prefix .= '_';
# prepend the prefix to the table names
@tables = map { $prefix.$_ } @tables;


unless (defined $user and defined $pwd ) {
	die "Fatal: You must specify database username (-u) and password (-p) AND core-ortholog set name (-s).\n";
}

if ($create) {
	&create_tables($prefix);
	print "OK.\n";
	exit;
}

unless (defined $setname) { croak "Fatal: You must specify the core-ortholog set name (-s).\n" }

my $infile = shift @ARGV or die "Fatal: Argument INFILE missing\n";

my $tmpfile = File::Temp->new();

my $faobj = Seqload::Fasta->open($infile);
while (my ($hdr, $seq) = $faobj->next_seq()) {
	my @line = split(/\|/, $hdr);
	printf $tmpfile "%s,%s,%s,%s,%s,%s\n", 
		$line[1], 
		$setname,
		$line[0], 
		File::Spec->catfile($prefix, $line[1], $line[1] . '_prot'),
		$line[2],
		$seq;
}
$faobj->close();

my $loadquery = "LOAD DATA LOCAL INFILE '$tmpfile' IGNORE INTO TABLE $table
	FIELDS TERMINATED BY ',' (
		taxon,
		orthoset,
		hmm,
		blastdb,
		header,
		sequence)";
my $updatequery = "UPDATE $table SET orthoset = '$setname' WHERE orthoset IS NULL";

my $dbh = DBI->connect("DBI:mysql:$dbname:$dbserver", $user, $pwd);
my $sql = $dbh->prepare($loadquery);
$sql->execute() or die;
$sql->finish();
$dbh->disconnect;

print "Successfully loaded $infile into $dbname on $dbserver.\n";
exit; 

sub drop_tables {
	my $prefix = shift;
	my $dbh = DBI->connect("DBI:mysql:$dbname:$dbserver", $user, $pwd)
		or die "Could not connect to MySQL database server: $!\n";
	print 'Dropping tables: ', join(", $prefix", @tables), "\n";
	foreach my $table (@tables) {
		$dbh->do("DROP TABLE IF EXISTS $table") or die "Could not execute drop query: $!\n";
	}
}


my %create_table = (
	$prefix . 'blast_dbs' => "CREATE TABLE `" . $prefix . "blast_dbs` (
		`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
		`taxon_id` int(10) unsigned DEFAULT NULL,
		`blastdb_path` varchar(255) DEFAULT NULL,
		PRIMARY KEY (`id`)
		) ENGINE=MyISAM DEFAULT CHARSET=latin1",
	
	$prefix . 'ogs' => "CREATE TABLE `" . $prefix . "o_ogs` (
			`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
			`name` varchar(255) DEFAULT NULL,
			PRIMARY KEY (`id`)
		) ENGINE=MyISAM DEFAULT CHARSET=latin1",

);

sub create_tables {
	my $prefix = shift;
	my $sql;
	my $query_drop ;
	my $query = "CREATE TABLE $table (
		id          INT(11) AUTO_INCREMENT PRIMARY KEY,
		taxon       VARCHAR(255) NOT NULL,
		orthoset    VARCHAR(255) NOT NULL,
		hmm         VARCHAR(255) NOT NULL,
		blastdb     VARCHAR(255) NOT NULL, INDEX (blastdb),
		header      VARCHAR(255) NOT NULL, INDEX (header),
		sequence    MEDIUMBLOB)";

	my $dbh = DBI->connect("DBI:mysql:$dbname:$dbserver", $user, $pwd);
	print "Dropping tables:\n";
	foreach my $table (@tables) {
		$query_drop = "DROP TABLE IF EXISTS $table";
		print "$query_drop;\n";
		$dbh->do($query_drop) or die "$!";
	}
	$dbh->do($_) or die "$!" foreach values %create_table;
		$dbh->disconnect;
}

#--------------------------------------------------
# 
# CREATE TABLE `o_ortholog_set` (
#   `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
#   `set_id` int(10) unsigned DEFAULT NULL,
#   `ortholog_gene_id` int(10) unsigned DEFAULT NULL,
#   `sequence_pair` int(10) unsigned DEFAULT NULL,
#   PRIMARY KEY (`id`)
# ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
# 
# CREATE TABLE `o_sequence_pairs` (
#   `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
#   `taxon_id` int(10) unsigned DEFAULT NULL,
#   `ogs_id` int(10) unsigned DEFAULT NULL,
#   `aa_seq` int(10) unsigned DEFAULT NULL,
#   `nt_seq` int(10) unsigned DEFAULT NULL,
#   `date` int(10) unsigned DEFAULT NULL,
#   `user` int(10) unsigned DEFAULT NULL,
#   PRIMARY KEY (`id`)
# ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
# 
# CREATE TABLE `o_sequences_aa` (
#   `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
#   `sequence` mediumblob,
#   `user` int(10) unsigned DEFAULT NULL,
#   `date` int(10) unsigned DEFAULT NULL,
#   PRIMARY KEY (`id`)
# ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
# 
# CREATE TABLE `o_sequences_nt` (
#   `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
#   `sequence` mediumblob,
#   `user` int(10) unsigned DEFAULT NULL,
#   `date` int(10) unsigned DEFAULT NULL,
#   PRIMARY KEY (`id`)
# ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
# 
# CREATE TABLE `o_set_details` (
#   `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
#   `description` tinyblob,
#   PRIMARY KEY (`id`)
# ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
# 
# CREATE TABLE `o_taxa` (
#   `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
#   `name` varchar(20) DEFAULT NULL,
#   `longname` varchar(255) DEFAULT NULL,
#   PRIMARY KEY (`id`)
# ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
# 
# CREATE TABLE `o_users` (
#   `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
#   `name` varchar(255) DEFAULT NULL,
#   PRIMARY KEY (`id`)
# ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
#-------------------------------------------------- 
